# Generated by Django 3.1.4 on 2021-01-21 02:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerride', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerride',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 20, 14, 47, 7, 345660)),
        ),
        migrations.AddField(
            model_name='offerride',
            name='destination',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='offerride',
            name='source',
            field=models.CharField(default='', max_length=100),
        ),
    ]
