# Generated by Django 3.1.4 on 2021-01-29 01:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerride', '0002_auto_20210120_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerride',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 28, 13, 38, 56, 679769)),
        ),
    ]
