# Generated by Django 3.1.4 on 2021-01-29 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offerride', '0003_auto_20210128_1338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfferRide',
        ),
    ]
